config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ActiveAdmin.routes(self)

  namespace :docs do
    get '/', to: 'doctors#index'
    get '/myclinic', to: 'doctors#my_clinic', as: "myclinic"
    resources :appointments, only: [:index, :create, :edit, :destroy]
    get '/dates', to: 'appointments#get_appointments'
    resources :users
    resources :products
    resources :balance_sheet_entries, :path => "cuentas" do
      resources :balance_sheet_entry_details, :path => "detalles"
    end
    # resources :balance_sheet_entries, :path => "cuentas", :as => :cuentas
    
    post '/image', to: 'patients#upload_image'
    post '/image/:id', to: 'patients#show_image'
    delete '/image/:id', to: 'patients#delete_image'
    post '/update_image/:id', to: 'patients#update_image'
    resources :patients
    
    resources :answers
    resources :choice_questions
    resources :choices
    resources :questions
    
    resources :histories

    post 'new_history_entry/', to: 'histories#create_entry'
    post 'update_history_entry/:id', to: 'histories#update_entry'
    post 'show_history_entry/:id', to: 'histories#show_entry'
    delete 'history_entry/:id', to: 'histories#delete_entry'
  end


  get '/no_clinic', to: 'pages#no_clinic'

end

app/models/docs.rb
module Docs
  def self.table_name_prefix
    'docs_'
  end
end

app/controllers/docs/answers_controller.rb
class Docs::AnswersController < Docs::DoctorsController

  private

    def answer_params
      params.require(:answer).permit(:choice_id, :choice_question_id, :history_id)
    end
end

app/controllers/docs/appointments_controller.rb
class Docs::AppointmentsController < Docs::DoctorsController
  before_action :ensure_json_request, only: [:show]
  before_action :set_appointment_schedule, only: [:destroy]

  def index
    @appointment = Appointment.new
  end

  def get_appointments
    @appointments = current_user.appointment_schedules
  end

  def create
    shedules = search_end(appointment_params[:timespan])
    @appointment = current_user.appointments.new(appointment_params.except(:timespan))
    respond_to do |format|
      if @appointment.save
        begin
          @appointment.appointment_schedules.create! shedules
        rescue ActiveRecord::RecordInvalid => invalid
          @appointment.destroy
          format.html { redirect_to docs_appointments_path, notice: { msg: 'Error en la fecha de programación de la cita', class: "danger"} }
          format.json { render json: @appointment.appointment_schedules.errors, status: :unprocessable_entity }
        end
        format.html { redirect_to docs_appointments_path, notice: 'La cita fue programada exitosamente.' }
      else
        format.html { render :index, notice: 'La cita no pudo ser programada.' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointment_schedule.destroy
    respond_to do |format|
      format.html { redirect_to docs_appointments_path, notice: 'La cita fue eliminada exitosamente.' }
    end
  end

  private
    def appointment_params
      params.require(:appointment).permit(:patient_id, :description, :price, timespan: [])
    end

    def set_appointment_schedule
      @appointment_schedule = AppointmentSchedule.find(params[:id])
    end
    
    # This function helps to separate modules selected in calendar
    # in order to store each one into table apointment_modules as a single record
    # params:
    #   total_values type array <-- appointment_params[:timespan]
    def search_end total_values = []
      # declare return variable as an array
      data = []
      # check total_values is an array
      case total_values
        when Array then
          # with a :start = first time selected in calendar and an empty :end
          data.push({start: total_values[0].to_time, end:""})

          # iterates total_values
          total_values.each_with_index do |time, i|
            # if next value is not empty is because current item is not the last one
            if !total_values[i + 1].blank?
              # if current value + 30 minutes is not equal to next value is because 
              # the module is complete then
              if !(total_values[i].to_time + 30.minutes == total_values[i + 1].to_time)
                # store in :end current value + 30 minutes to close module
                data[data.size - 1][:end] = total_values[i].to_time + 30.minutes
                # and initialize the next one with :start next value and an empty :end
                data.push({start:total_values[i + 1], end:""})
              end
            end
          end
          # when total_value's iteration is done fill in :end with last item + 30 minutes
          data[data.size - 1][:end] = total_values[total_values.size - 1].to_time + 30.minutes
      end
      # returns the data array of modules
      return data
    end
end

app/controllers/docs/balance_sheet_entries_controller.rb
class Docs::BalanceSheetEntriesController < Docs::DoctorsController
  helper_method :sort_column, :sort_direction
  before_action :set_details, only: [:edit, :update]
  before_action :set_detail, only: [:edit, :update]
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  
  def index
    @balances = current_user.clinic.balance_sheet_entries.order("#{sort_column} #{sort_direction}").paginate(:page => params[:page], :per_page => 25)
    @balances = @balances.by_range(params[:from],params[:to]) unless ( params[:from].blank? || params[:to].blank? )
    @balances = @balances.by_month(Date.today.month) if ( params[:from].blank? || params[:to].blank? )
  end

  def show
    @balance_sheet_entry_details = @balance_sheet_entry.balance_sheet_entry_details.order("#{sort_column_entry} #{sort_direction_entry}")
                             .paginate(:page => params[:page], :per_page => 25)
    @balance_sheet_entry_details = @balance_sheet_entry_details.by(params[:search]) unless params[:search].blank?
  end

  def new
    @balance_sheet_entry = current_user.clinic.balance_sheet_entries.new
    @balance_sheet_entry.balance_sheet_entry_details.build
  end

  def edit
  end

  def create
    @balance_sheet_entry = current_user.clinic.balance_sheet_entries.build(entry_params)
    # @balance_sheet_entry.balance_sheet_entry_details.build(entry_params[:balance_sheet_entry_details_attributes])
    # raise entry_params.to_yaml
    respond_to do |format|
      if @balance_sheet_entry.save
        format.html { redirect_to edit_docs_balance_sheet_entry_path(@balance_sheet_entry), notice: 'La entrada fue creada exitosamente.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @balance_sheet_entry.update(entry_params)
        format.html { redirect_to edit_docs_balance_sheet_entry_path(@balance_sheet_entry), notice: 'La entrada fue actualizada exitosamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @balance_sheet_entry.destroy
    respond_to do |format|
      format.html { redirect_to docs_balance_sheet_entries_url, notice: 'La entrada fue eliminada exitosamente' }
    end
  end

  private

    def set_entry
      @balance_sheet_entry = current_user.clinic.balance_sheet_entries.find(params[:id])
    end

    def set_detail
      set_entry
      @detail = @balance_sheet_entry.balance_sheet_entry_details.build
    end

    def set_details
      set_entry
      @details = @balance_sheet_entry.balance_sheet_entry_details
    end

    def entry_params
      params.require(:balance_sheet_entry).permit(:title, :description, :doctor_id, :patient_id, :transaction_date, :payment_status, balance_sheet_entry_details_attributes: [:title, :description, :amount, :transaction_type_id])
    end

    def sort_column
      ["transaction_date", "title", "doctor_id", "patient_id", "amount"].include?(params[:sort]) ? params[:sort] : "transaction_date"
    end

    def sort_column_entry
      [ "id",
        "title", 
        "incoming", 
        "outgoing" ].include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction_entry
      ["asc", "desc"].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def sort_direction
      ["asc", "desc"].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/controllers/docs/balance_sheet_entry_details_controller.rb
class Docs::BalanceSheetEntryDetailsController < Docs::DoctorsController
  helper_method :sort_column, :sort_direction
  before_action :set_entry
  before_action :set_detail, only: [:show, :edit, :update, :destroy]
  
  # def index
  #   @balance_sheet_entries = @balance_sheet.balance_sheet_entries.pagado.order("#{sort_column} #{sort_direction}")
  #                            .paginate(:page => params[:page], :per_page => 25)
  #   @balance_sheet_entries = @balance_sheet_entries.by(params[:search]) unless params[:search].blank?
  # end

  def show
  end

  # def new
  #   @balance_sheet_entry_detail = @balance_sheet_entry.balance_sheet_entry_details.new
  # end

  def edit
  end

  def create
    @balance_sheet_entry_detail = @balance_sheet_entry.balance_sheet_entry_details.new(entry_params)
    respond_to do |format|
      if @balance_sheet_entry_detail.save
        format.html { redirect_to docs_balance_sheet_entry_path(@balance_sheet_entry), notice: 'El detalle fue creado exitosamente.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @balance_sheet_entry_detail.update(entry_params)
        format.html { redirect_to edit_docs_balance_sheet_entry_path(@balance_sheet_entry), notice: 'El detalle fue actualizado exitosamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @balance_sheet_entry_detail.destroy
    respond_to do |format|
      format.html { redirect_to edit_docs_balance_sheet_entry_path(@balance_sheet_entry), notice: 'El detalle fue eliminado exitosamente' }
    end
  end

  private
    def set_entry
      @balance_sheet_entry = current_user.clinic.balance_sheet_entries.find(params[:balance_sheet_entry_id])
    end

    def set_detail
      set_entry
      @balance_sheet_entry_detail = @balance_sheet_entry.balance_sheet_entry_details.find(params[:id])
    end

    def entry_params
      params.require(:balance_sheet_entry_detail).permit(:title, :description, :amount, :transaction_type_id)
    end

    def sort_column
      [ "id",
        "title", 
        "incoming", 
        "outgoing" ].include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      ["asc", "desc"].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/docs/choice_questions_controller.rb
class Docs::ChoiceQuestionsController < Docs::DoctorsController

  private

    def choice_question_params
      params.require(:choice_question).permit(:choice_id, :question_id)
    end
end

app/controllers/docs/choices_controller.rb
class Docs::ChoicesController < Docs::DoctorsController

  private

    def choice_params
      params.require(:choice).permit(:choice_text)
    end
end

app/controllers/docs/clinics_controller.rb
class Docs::ClinicsController < Docs::DoctorsController

  def show
    @clinic = current_user.clinic
  end
end

app/controllers/docs/doctors_controller.rb
class Docs::DoctorsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_clinic!
  layout "doctors_app"

  def index
  end

  def my_clinic
    @clinic = current_user.clinic
  end

  def authenticate_clinic!
    unless current_user.Administrator?
      clinic = current_user.clinic
      if clinic&.status == false || !clinic
        redirect_to no_clinic_path 
      end
    end
  end

  def ensure_json_request  
    return if request.format == :json
    render :nothing => true, :status => 406  
  end
end

app/controllers/docs/histories_controller.rb
class Docs::HistoriesController < Docs::DoctorsController
  before_action :set_history, except: [:delete_entry]
  before_action :set_patient, except: [:delete_entry]

  def create_entry
    @history_entry = @history.history_entries.new(history_entry_params)
    if @history_entry.save
      if params['history_entry']['attachment']
        Attachment.create(image: params['history_entry']['attachment'], imageable: @history_entry)
      end
      redirect_to docs_patient_path(@patient), notice: 'La entrada fue creada exitosamente.'
    else
      redirect_to docs_patient_path(@patient), notice: { msg: 'Error al crear la entrada la historia', class: "danger"}
    end
  end

  def show_entry
      @history_entry = HistoryEntry.find(params['id'])
      if @history_entry.attachments.count > 0
        @attachment = @history_entry.attachments.last.image.url(:mini)
      else
        @attachment = ''
      end
      
      render json: {history_entry: @history_entry, attachment: @attachment}
  end

  def update_entry
    @history_entry = HistoryEntry.find(params['id_history_entry'])
    @history_entry.update(pain: false, gingivitis: false)
    if @history_entry.update(history_entry_params)
      if params['history_entry']['attachment']
        if @history_entry.attachments.count > 0
          @history_entry.attachments.last.destroy
        end
        Attachment.create(image: params['history_entry']['attachment'], imageable: @history_entry)
      end
      redirect_to docs_patient_path(@patient), notice: 'La entrada fue actualizada exitosamente.'
    else
      redirect_to docs_patient_path(@patient), notice: { msg: 'Error al actualizar la entrada la historia', class: "danger"}
    end
  end

  def delete_entry
    render json: HistoryEntry.find(params['id']).destroy
  end

  def update
    respond_to do |format|
      if @patient.history.update(history_params)
        Answer.where(history: @patient.history).destroy_all.to_json
        params[:history][:questions].each do |a,i|
          # ChoiceQuestion.where(choice: Choice.find(i.to_i), question: Question.find(a.to_i)).destroy_all
          # cq = ChoiceQuestion.create! choice: Choice.find(i.to_i), question: Question.find(a.to_i)
          Answer.create! choice_question: ChoiceQuestion.where(choice: i.to_i, question_id: a.to_i).take, history: @patient.history, choice: Choice.find(i.to_i)
        end
        format.html { redirect_to docs_patient_path(@patient), notice: 'La historia fue actualizada exitosamente.' }
      else
        format.html { redirect_to docs_patient_path(@patient), notice: { msg: 'Error al actualizar la historia', class: "danger"} }
      end
    end
  end

  private

    def set_history
      @history = History.find(params[:id])
    end

    def set_patient
      set_history
      @patient = @history.patient
    end

    def history_params
      params.require(:history).permit(:code, :patient_id, :doctor_id, :family_history, :overview, :questions => [] )
    end

    def history_entry_params
      params.require(:history_entry).permit(:reason_for_the_visit, :pain, :gingivitis, :control, :prosthetic_restoration, :other, :current_disease, :appearance, :face, :lips_and_commissure, :nodes, :cheeks, :mucosa, :gum, :tongue, :palate, :rx_panoramic, :rx_coronal, :rx_periapical, :observations )
    end
end

app/controllers/docs/products_controller.rb
class Docs::ProductsController < Docs::DoctorsController
	before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to docs_product_path(@product), notice: 'El producto fue creado exitosamente.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to docs_product_path(@product), notice: 'El producto fue actualizado exitosamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to docs_products_path, notice: 'El producto fue eliminado exitosamente' }
    end
  end

  private
  	def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :code, :price, :expiration_date, :characteristics, :status)
    end
end

app/controllers/docs/questions_controller.rb
class Docs::QuestionsController < Docs::DoctorsController
  private

    def question_params
      params.require(:question).permit(:question_text)
    end
end

app/controllers/docs/users_controller.rb
class Docs::UsersController < Docs::DoctorsController

  def index
  end
end

app/helpers/docs/appointments_helper.rb
module Docs::AppointmentsHelper
end

app/helpers/docs/products_helper.rb
module Docs::ProductsHelper
end

app/helpers/docs/users_helper.rb
module Docs::UsersHelper
end

app/views/docs/balance_sheet_entries/_balance_sheet_entries.erb
<table class="table">
  <thead class="thead-products">
    <tr>
      <th><%= sortable "#", ["id"] %></th>
      <th><%= sortable "Fecha", ["transaction_date"] %></th>
      <th><%= sortable "Título", ["title"] %></th>
      <th><%= sortable "Doctor", ["doctor_id"] %></th> 
      <th><%= sortable "Paciente", ["patient_id"] %></th> 
      <th><%= sortable "Monto", ["amount"] %></th> 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% a = 0 %>
    <% @balances.each do |balance| %>
      <tr>
        <td><%= balance.id %></td>
        <td><%= balance.transaction_date %></td>
        <td><%= balance.title %></td>
        <td><%= balance.doctor.full_name %></td>
        <td><%= balance.patient.full_name %></td>
        <td><%= a = balance.balance_sheet_entry_details.where("transaction_type_id IN (?)",TransactionType.incoming.map(&:id)).map(&:amount).sum - balance.balance_sheet_entry_details.where("transaction_type_id IN (?)",TransactionType.outgoing.map(&:id)).map(&:amount).sum %></td>
        <td><%= link_to 'Ver', docs_balance_sheet_entry_path(balance) %></td>
        <td><%= link_to 'Editar', edit_docs_balance_sheet_entry_path(balance) %></td>
        <td><%= link_to 'Eliminar', docs_balance_sheet_entry_path(balance), method: :delete, data: { confirm: '¿Estás seguro de eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @balances, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>

app/views/docs/balance_sheet_entries/_form.html.erb
<%= semantic_form_for ([:docs, @balance_sheet_entry]) do |f| %>
  <% if @balance_sheet_entry.errors.any? %>
    <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <ul>
      <% @balance_sheet_entry.errors.full_messages.each do |m| %>
        <li>
          <%= m %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-6">
      <%= f.inputs do %>
        <%= f.input :transaction_date, label: "Fecha de Transacción", start_year: 2000 %>
        <%= f.input :title, label: false, placeholder: 'Título' %>
        <%= f.input :description, label: false, placeholder: 'Descripción', :input_html => { :rows => 5} %>
      <% end %>
    </div>
    <div class="col-sm-6">
      <%= f.inputs do %>
        <%= f.input :doctor_id, label: "Doctor", :as => :select, :collection => Doctor.all.map{|d| ["#{d.first_name} #{d.last_name}", d.id]} %>
        <%= f.input :patient_id, label: "Paciente", :as => :select, :collection => Patient.all.map{|p| ["#{p.first_name} #{p.last_name}", p.id]} %>
        <%= f.input :payment_status, label: "¿Pagado?", :as => :select, :include_blank => false %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">&nbsp;</div>
    <div class="col-sm-12">
      <h6>Detalle</h6>
    </div>
    <div class="col-sm-12">&nbsp;</div>
  </div>
  <div class="row">
    <div class="col-sm-12">
        <div class="col-sm-6">
            <%= text_field_tag :title, nil, name: "balance_sheet_entry[balance_sheet_entry_details_attributes][0][title]",placeholder: "Título", class: "form-control" %>
            <br>
            <%= text_area_tag :description, nil, placeholder: "Descripción", :rows => 5, name: "balance_sheet_entry[balance_sheet_entry_details_attributes][0][description]", class: "form-control" %>
        </div>
        <div class="col-sm-6">
            <%= text_field_tag :amount, nil, placeholder: "Monto", name: "balance_sheet_entry[balance_sheet_entry_details_attributes][0][amount]", class: "form-control" %>
            <br>
            <label for="transaction_type_id">Tipo de Transacción</label>
            <%= select_tag "balance_sheet_entry[balance_sheet_entry_details_attributes][0][transaction_type_id]", options_from_collection_for_select(TransactionType.all, :id, :title), class: "form-control", :include_blank => 'Seleccione un Tipo de Transacción' %>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">&nbsp;</div>
    <div class="col-sm-12">
      <table class="table">
        <thead> 
          <tr> 
            <th>#</th>
            <th>Título</th> 
            <th class="right">Ingreso</th>
            <th class="right">Egreso</th>
            <th colspan="3" class="no-print">&nbsp;</th>
          </tr>
        </thead> 
        <tbody class="smaller">
          <% out = inc = 0 %>
          <% if !@details.blank? %>
            <% @details.each do |entry| %>
              <% unless entry.id.blank? %>
                <tr> 
                  <td><%= entry.id %></td> 
                  <td><%= entry.title.truncate(45) if !entry.title.blank? %></td>
                  <% inc += entry.amount if entry.transaction_type.incoming? %>
                  <% out += entry.amount if entry.transaction_type.outgoing? %>
                  <td class="right"><%= entry.amount if entry.transaction_type.incoming? %></td> 
                  <td class="right"><%= entry.amount if entry.transaction_type.outgoing? %></td> 
                  <td colspan="3" class="no-print right">
                    <%= link_to '<i class="icon-eye icons"></i>'.html_safe, docs_balance_sheet_entry_balance_sheet_entry_detail_path(@balance_sheet_entry, entry), title: "Ver", alt: "Ver" %>&nbsp;&nbsp;
                    <%= link_to '<i class="icon-pencil icons"></i>'.html_safe, edit_docs_balance_sheet_entry_balance_sheet_entry_detail_path(@balance_sheet_entry, entry), title: "Editar", alt: "Editar" %>&nbsp;&nbsp;
                    <%= link_to '<i class="icon-trash icons"></i>'.html_safe, docs_balance_sheet_entry_balance_sheet_entry_detail_path(@balance_sheet_entry, entry), method: :delete, data: { confirm: '¿Estás seguro de eliminar?' } %>
                  </td> 
                </tr> 
              <% end %>
            <% end %>
          <% else %>
            <tr>
              <td colspan="10">No hay detalle para esta entrada</td>
            </tr>
          <% end %>
        </tbody>
        <tfoot class="right">
          <tr>
            <td colspan="2">
              <h4>Sub-total</h4>
            </td>
            <td>
              <h4><%= inc %></h4>
            </td>
            <td>
              <h4><%= out %></h4>
            </td>
            <td colspan="3">
              &nbsp;
            </td>
          </tr>
          <tr>
            <td colspan="2">
              <h4>Total</h4>
            </td>
            <td>
              &nbsp;
            </td>
            <td>
              <h4><%= inc - out %></h4>
            </td>
            <td colspan="3">
              &nbsp;
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
    <div class="col-sm-12">&nbsp;</div>
  </div>
  <div class="row">
    <div class="col-sm-12">
    <%= f.actions do %>
      <%= f.action :submit, :label => " Guardar ", :button_html => { :class => "btn btn-success" } %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/docs/balance_sheet_entries/edit.html.erb
<%= render 'form' %>
<br>
<div class="row">
  <div class="col-sm-12">
  <%= link_to 'Mostrar', docs_balance_sheet_entry_path(@balance_sheet_entry), class: "btn btn-primary" %>
  
  <%= link_to 'Regresar', docs_balance_sheet_entries_path, class: "btn btn-info" %>
  </div>
</div>

app/views/docs/balance_sheet_entries/index.html.erb
<h1 class="section-title">Cuentas</h1>

<div class="row row-fix">
  <div class="col-sm-12">
    <%= form_tag docs_balance_sheet_entries_path, :method => 'get', id: "search_form", class: "form-inline" do %>
      <%= hidden_field_tag :direction, params[:direction] %>
      <%= hidden_field_tag :sort, params[:sort] %>
      <div class="form-group">
        <%= text_field_tag :from, params[:from], class: "form-control",  placeholder: "Desde",  "data-provide": 'datepicker', readonly: true %>
      </div>
      <div class="form-group">
        <%= text_field_tag :to, params[:to], class: "form-control",  placeholder: "Hasta",  "data-provide": 'datepicker', readonly: true %>
      </div>
      <div class="form-group">&nbsp;&nbsp;
      <%= submit_tag "Buscar", :name => nil, class: "btn btn-success" %>
      </div>
      <div class="form-group">&nbsp;&nbsp;
      <%= link_to 'Nueva Entrada', new_docs_balance_sheet_entry_path, class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

<div class="row row-fix" id="data">
  <%= render "balance_sheet_entries" %>
</div>

app/views/docs/balance_sheet_entries/index.json.erb
{
  "data": "<%= escape_javascript(render "balance_sheet_entries") %>"
}

app/views/docs/balance_sheet_entries/new.html.erb
<%= render 'form' %>
<br>
<div class="row">
  <div class="col-sm-12">
    <%= link_to 'Regresar', docs_balance_sheet_entries_path, class: "btn btn-info" %>
  </div>
</div>

app/views/docs/balance_sheet_entries/show.html.erb
<div class="row">
  <div class="col-sm-8">
    <strong>
      <%= @balance_sheet_entry.title %>
    </strong>
  </div>
  <div class="col-sm-4 no-print">
    <%= link_to 'Editar', edit_docs_balance_sheet_entry_path(@balance_sheet_entry), class: "btn btn-success" %>
    <%= link_to "#", class: "btn btn-danger", onclick: "window.print(); return false;", alt: "imprimir", title: "imprimir" do%>
      <i class="icon-printer icons"></i>
    <% end %>
    <%= link_to 'Atrás', docs_balance_sheet_entries_path, class: "btn btn-info" %>  
  <br class="no-print">
  <br class="no-print">
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <p>
      <strong>Descripción:</strong>
      <%= @balance_sheet_entry.description %>
    </p>
   
    <p>
      <strong>Doctor:</strong>
      <%= @balance_sheet_entry.doctor.full_name %>&nbsp;&nbsp;
    
      <strong>Paciente:</strong>
      <%= @balance_sheet_entry.patient.full_name %>&nbsp;&nbsp;
    
      <strong>Fecha de transacción:</strong>
      <%= @balance_sheet_entry.transaction_date %>&nbsp;&nbsp;
    
      <strong>Estado del pago:</strong>
      <%= @balance_sheet_entry.pagado? ? "Pagado" : "Pendiente"  %>
    </p>
  </div>
</div>
<br>
<div class="row">
  <div class="col-sm-12">
    <%= render 'docs/balance_sheet_entry_details/balance_sheet_entry_details' %>
  </div>
</div>