config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ActiveAdmin.routes(self)

  namespace :docs do
    get '/', to: 'doctors#index'
    get '/myclinic', to: 'doctors#my_clinic', as: "myclinic"
    resources :appointments, only: [:index, :create, :edit, :destroy]
    get '/dates', to: 'appointments#get_appointments'
    resources :users
    resources :products
    resources :balance_sheet_entries, :path => "cuentas" do
      resources :balance_sheet_entry_details, :path => "detalles"
    end
    # resources :balance_sheet_entries, :path => "cuentas", :as => :cuentas
    
    post '/image', to: 'patients#upload_image'
    post '/image/:id', to: 'patients#show_image'
    delete '/image/:id', to: 'patients#delete_image'
    post '/update_image/:id', to: 'patients#update_image'
    resources :patients
    
    resources :answers
    resources :choice_questions
    resources :choices
    resources :questions
    
    resources :histories

    post 'new_history_entry/', to: 'histories#create_entry'
    post 'update_history_entry/:id', to: 'histories#update_entry'
    post 'show_history_entry/:id', to: 'histories#show_entry'
    delete 'history_entry/:id', to: 'histories#delete_entry'
  end


  get '/no_clinic', to: 'pages#no_clinic'

end

app/models/history.rb
class History < ApplicationRecord

  belongs_to :doctor, class_name: User,
                      foreign_key: :doctor_id
  belongs_to :patient, class_name: User,
                      foreign_key: :patient_id

  has_many :answers
  has_many :history_entries, dependent: :destroy

  has_many :attachments, as: :imageable, dependent: :destroy

  validates :doctor_id, :patient_id, :code, presence: true
end

app/controllers/docs/histories_controller.rb
class Docs::HistoriesController < Docs::DoctorsController
  before_action :set_history, except: [:delete_entry]
  before_action :set_patient, except: [:delete_entry]

  def create_entry
    @history_entry = @history.history_entries.new(history_entry_params)
    if @history_entry.save
      if params['history_entry']['attachment']
        Attachment.create(image: params['history_entry']['attachment'], imageable: @history_entry)
      end
      redirect_to docs_patient_path(@patient), notice: 'La entrada fue creada exitosamente.'
    else
      redirect_to docs_patient_path(@patient), notice: { msg: 'Error al crear la entrada la historia', class: "danger"}
    end
  end

  def show_entry
      @history_entry = HistoryEntry.find(params['id'])
      if @history_entry.attachments.count > 0
        @attachment = @history_entry.attachments.last.image.url(:mini)
      else
        @attachment = ''
      end
      
      render json: {history_entry: @history_entry, attachment: @attachment}
  end

  def update_entry
    @history_entry = HistoryEntry.find(params['id_history_entry'])
    @history_entry.update(pain: false, gingivitis: false)
    if @history_entry.update(history_entry_params)
      if params['history_entry']['attachment']
        if @history_entry.attachments.count > 0
          @history_entry.attachments.last.destroy
        end
        Attachment.create(image: params['history_entry']['attachment'], imageable: @history_entry)
      end
      redirect_to docs_patient_path(@patient), notice: 'La entrada fue actualizada exitosamente.'
    else
      redirect_to docs_patient_path(@patient), notice: { msg: 'Error al actualizar la entrada la historia', class: "danger"}
    end
  end

  def delete_entry
    render json: HistoryEntry.find(params['id']).destroy
  end

  def update
    respond_to do |format|
      if @patient.history.update(history_params)
        Answer.where(history: @patient.history).destroy_all.to_json
        params[:history][:questions].each do |a,i|
          # ChoiceQuestion.where(choice: Choice.find(i.to_i), question: Question.find(a.to_i)).destroy_all
          # cq = ChoiceQuestion.create! choice: Choice.find(i.to_i), question: Question.find(a.to_i)
          Answer.create! choice_question: ChoiceQuestion.where(choice: i.to_i, question_id: a.to_i).take, history: @patient.history, choice: Choice.find(i.to_i)
        end
        format.html { redirect_to docs_patient_path(@patient), notice: 'La historia fue actualizada exitosamente.' }
      else
        format.html { redirect_to docs_patient_path(@patient), notice: { msg: 'Error al actualizar la historia', class: "danger"} }
      end
    end
  end

  private

    def set_history
      @history = History.find(params[:id])
    end

    def set_patient
      set_history
      @patient = @history.patient
    end

    def history_params
      params.require(:history).permit(:code, :patient_id, :doctor_id, :family_history, :overview, :questions => [] )
    end

    def history_entry_params
      params.require(:history_entry).permit(:reason_for_the_visit, :pain, :gingivitis, :control, :prosthetic_restoration, :other, :current_disease, :appearance, :face, :lips_and_commissure, :nodes, :cheeks, :mucosa, :gum, :tongue, :palate, :rx_panoramic, :rx_coronal, :rx_periapical, :observations )
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= semantic_form_for @history do |f| %>
  <%= f.inputs do %>
    <%= f.input :code %>
    <%= f.input :patient_id %>
    <%= f.input :doctor_id %>
    <%= f.input :family_history %>
    <%= f.input :overview %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Patient</th>
      <th>Doctor</th>
      <th>Family history</th>
      <th>Overview</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.code %></td>
        <td><%= history.patient_id %></td>
        <td><%= history.doctor_id %></td>
        <td><%= history.family_history %></td>
        <td><%= history.overview %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @history.code %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @history.patient_id %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @history.doctor_id %>
</p>

<p>
  <strong>Family history:</strong>
  <%= @history.family_history %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @history.overview %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>